version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "4000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend_network  # This connects to the shared network

networks:
  backend_network:
    external: true  # Reuse an existing external network
